### ISSUE TITLE
shlong-django

### ISSUE THREAD

**Issue by micahwalter** [migurski/shlong#1]
hey there,
I was bored one night and decided to make a shlong-django project so I could easily have a url shortener up on heroku, written in python... 

its a branch on my fork, so please have a look here https://github.com/micahwalter/shlong/tree/shlong-django

I'm not sure how to submit a pull req. to a new branch on github... ?

let me know what ya think

micah

**Comment by migurski** [comment]
Sorry I never responded to this PR!

**Comment by micahwalter** [comment]
I'm over it ;) Just doing some GH house cleaning today ....
